# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('vat_tin_no', models.CharField(blank=True, max_length=12)),
                ('invoice_no', models.CharField(blank=True, max_length=10)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('po_no', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=20)),
                ('per', models.CharField(choices=[('mg', 'MG'), ('kg', 'KG'), ('inch', 'INCH')], default='mg', max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Buyer')),
            ],
        ),
    ]
